// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulpqrurfmkhsbwrhrzzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVscHFydXJmbWtoc2J3cmhyenptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTUzNzgsImV4cCI6MjA2NTU3MTM3OH0.afRno6DGga8xlosfnDvj5fXDru76DA32ASRfImZLGkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);